import type { Metadata } from "next";
import { notoSans } from "@/libs/uitls/fonts";
import { COLOR_THEME } from "@/libs/uitls/constants";
import SnackbarProvider from "@/libs/snackbarProvider";
import { SnackbarComponent } from "@/components/organisms/snackbarComponent";
import { WindowTemplate } from "@/components/template/windowTemplate";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${notoSans.className} antialiased h-screen w-screen text-stone-800`}
        style={{
          backgroundColor: COLOR_THEME.bgGreen,
        }}
      >
        <SnackbarProvider>
          <SnackbarComponent />
          <WindowTemplate>{children}</WindowTemplate>
        </SnackbarProvider>
      </body>
    </html>
  );
}
